[package]
name = "chunky-vec"
description = """
A pin safe, append only vector never moves the backing store for an element.
"""
version = "0.1.0"
authors = ["Dan Glastonbury <dan.glastonbury@gmail.com>"]
edition = "2018"
license = "Apache-2.0/MIT"
repository = "https://github.com/djg/chunky-vec"
keywords = ["data-structure", "vector", "pin"]
categories = ["data-structures"]

[dependencies]

